name: "SonarQube Cache"
description: "Cache SonarQube packages."
author: "sonaractions"

outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key."
    value: ${{ steps.cache-sonar.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-sonar
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

branding:
  icon: "archive"
  color: "purple"

